-- CivilPH Supabase Schema (PostgreSQL)
-- Run this in the Supabase SQL Editor

-- 1. PROFILES TABLE
-- Extends auth.users to store public profile information
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  first_name TEXT,
  last_name TEXT,
  phone TEXT,
  role TEXT CHECK (role IN ('homeowner', 'engineer', 'admin')) DEFAULT 'homeowner',
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. ENGINEERS TABLE
-- Stores professional details for engineers
CREATE TABLE public.engineers (
  id UUID REFERENCES public.profiles(id) ON DELETE CASCADE PRIMARY KEY,
  title TEXT DEFAULT 'Civil Engineer',
  bio TEXT,
  specialties TEXT[] DEFAULT '{}',
  years_experience INTEGER DEFAULT 0,
  city TEXT,
  region TEXT,
  prc_license_number TEXT,
  verification_status TEXT CHECK (verification_status IN ('pending', 'verified', 'rejected')) DEFAULT 'pending',
  rating NUMERIC(3,2) DEFAULT 5.00,
  review_count INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. SERVICE PACKAGES
-- Services offered by engineers
CREATE TABLE public.service_packages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engineer_id UUID REFERENCES public.engineers(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC(12,2) NOT NULL,
  consultation_type TEXT NOT NULL, -- 'onsite_inspection', 'online_consultation', etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. APPOINTMENTS
-- Booking information
CREATE TABLE public.appointments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  client_id UUID REFERENCES public.profiles(id),
  engineer_id UUID REFERENCES public.engineers(id),
  service_package_id BIGINT REFERENCES public.service_packages(id),
  scheduled_date DATE NOT NULL,
  scheduled_time TIME NOT NULL,
  status TEXT CHECK (status IN ('pending', 'confirmed', 'completed', 'cancelled')) DEFAULT 'pending',
  location_address TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. REPORTS
-- Digital Structural Assessment Reports
CREATE TABLE public.reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  appointment_id UUID REFERENCES public.appointments(id) ON DELETE CASCADE,
  engineer_id UUID REFERENCES public.engineers(id),
  client_id UUID REFERENCES public.profiles(id),
  title TEXT NOT NULL,
  summary TEXT,
  findings TEXT,
  recommendations TEXT,
  estimated_cost_min NUMERIC(12,2),
  estimated_cost_max NUMERIC(12,2),
  document_url TEXT,
  status TEXT CHECK (status IN ('draft', 'submitted', 'acknowledged')) DEFAULT 'draft',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. REVIEWS
-- User ratings for engineers
CREATE TABLE public.reviews (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  appointment_id UUID REFERENCES public.appointments(id) ON DELETE CASCADE,
  client_id UUID REFERENCES public.profiles(id),
  engineer_id UUID REFERENCES public.engineers(id),
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. AUTOMATIC PROFILE CREATION ON SIGNUP
-- Trigger to insert profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, first_name, last_name, phone, role)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'firstName',
    new.raw_user_meta_data->>'lastName',
    new.raw_user_meta_data->>'phone',
    COALESCE(new.raw_user_meta_data->>'role', 'homeowner')
  );
  
  -- If the role is engineer, also create an entry in engineers table
  IF (new.raw_user_meta_data->>'role' = 'engineer') THEN
    INSERT INTO public.engineers (id) VALUES (new.id);
  END IF;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engineers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profiles." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Engineers Policies
CREATE POLICY "Engineers are viewable by everyone." ON public.engineers FOR SELECT USING (true);
CREATE POLICY "Engineers can update their own data." ON public.engineers FOR UPDATE USING (auth.uid() = id);

-- Appointments Policies
CREATE POLICY "Users can see their own appointments." ON public.appointments FOR SELECT 
USING (auth.uid() = client_id OR auth.uid() = engineer_id);
CREATE POLICY "Clients can create appointments." ON public.appointments FOR INSERT 
WITH CHECK (auth.uid() = client_id);
CREATE POLICY "Involved parties can update appointments." ON public.appointments FOR UPDATE 
USING (auth.uid() = client_id OR auth.uid() = engineer_id);

-- Service Packages Policies
CREATE POLICY "Service packages are viewable by everyone." ON public.service_packages FOR SELECT USING (true);
CREATE POLICY "Engineers can manage their own packages." ON public.service_packages FOR ALL 
USING (auth.uid() = engineer_id);

-- Reports Policies
CREATE POLICY "Involved parties can see reports." ON public.reports FOR SELECT 
USING (auth.uid() = client_id OR auth.uid() = engineer_id);
CREATE POLICY "Engineers can manage reports." ON public.reports FOR ALL 
USING (auth.uid() = engineer_id);

-- Reviews Policies
CREATE POLICY "Reviews are viewable by everyone." ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Clients can create reviews." ON public.reviews FOR INSERT 
WITH CHECK (auth.uid() = client_id);
